version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sca-backend-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sca
    ports:
      - "3306:3306"
